#!/bin/bash
while read MSG
do
    if [[ $disable = "true" ]]; then
        rm "$MSG"
        continue
    fi
    [[ $verbose = "true" ]] && echo [$0] Got path: $MSG
    if [[ $pretty = "true" ]]; then
        jq -j '.from' "$MSG"
        printf '> '
        jq -r '.text' "$MSG"
    else 
        cat $MSG
    fi
    [[ $verbose = "true" ]] &&echo [$0] Sending slowly...
    sleep 0.5
    [[ $verbose = "true" ]] &&echo [$0] Appending to log
    cat $MSG >> log.txt
    rm $MSG
done
