#!/bin/env python
import aiogram, os, json, logging, sys

perr = lambda x: print(f"[tg-recv] {str(x)}", file=sys.stderr)
bot = aiogram.Bot(os.environ["apikey"])
dp = aiogram.Dispatcher(bot)


@dp.message_handler(commands=["chatid"])
async def get_chat_id(message):
    await message.reply(message.chat.id)


@dp.channel_post_handler(content_types=["text", "photo"])
@dp.message_handler(content_types=["text", "photo"])
async def echo(message):
    user = message.from_user
    if user:

        name = user.first_name + " " + user.last_name + "@telegram"
    else:
        name = message.chat.title + "@" + message.chat.type + ".telegram"
    if "chat" in os.environ and str(message.chat.id) != os.environ["chat"]:
        perr(f"Chat id = {message.chat.id}")
        return
    # await bot.send_message(message.chat.id, "OK")
    if message.text:
        print(
            json.dumps({"text": message.text, "from": name, "protocol": "telegram"}),
            flush=True,
        )
    if message.photo:
        file_id = message.photo[-1].file_id
        file = await bot.get_file(file_id)
        url = bot.get_file_url(file.file_path)
        print(
            json.dumps(
                {
                    "text": "[sorry the url leaks bot token :( ]",
                    "image": url,
                    "from": name,
                    "protocol": "telegram",
                }
            ),
            flush=True,
        )


if __name__ == "__main__":
    aiogram.executor.start_polling(dp, skip_updates=True)
