#!/bin/env python
from os import environ
import sys, json
from vk_api import VkApi
from vk_api.longpoll import VkLongPoll, VkEventType

session = VkApi(token=environ["apikey"])
api = session.get_api()
perr = lambda x: print(f"[vk-recv] {str(x)}", file=sys.stderr)
xerr = lambda o: perr(str(dict(o)))
me = api.groups.getById()[0]
def handle_message(msg,name = None):
    perr("handling message")
    xerr(msg)
    if name is None:
        name = "VK"
        if msg['from_id'] < 0:
            name = api.groups.getById(group_id=-msg['from_id'])[0]["name"] + "@group.vk"
        else:
            user = api.users.get(user_ids=msg['from_id'])[0]
            name = user["first_name"] + " " + user["last_name"] + "@vk"
    if msg['text']:
        print(
            json.dumps({"text": msg['text'], "from": name, "protocol": "vk"}),
            flush=True,
        )
    for attachment in msg['attachments']:
        perr(attachment)
        if attachment["type"] == "photo":
            url = attachment["photo"]["sizes"][-1]["url"]
            print(
                json.dumps(
                    {"text": url, "image": url, "from": name, "protocol": "vk"}
                ),
                flush=True,
            )
    if 'fwd_messages' in msg:
        for fwd in msg['fwd_messages']:
            handle_message(fwd,name)

# print("[vk-recv] Testing vk api, my id:",me["id"],file=sys.stderr)
longpoll = VkLongPoll(session)
for event in longpoll.listen():
    # print("[vk-recv] Got event:",event.type,file=sys.stderr)
    if event.type == VkEventType.MESSAGE_NEW:
        if "chat" in environ and environ["chat"] != str(event.peer_id):
            continue
        if not event.to_me:
            continue
        # print("[vk-recv] Got peer:",event.peer_id,file=sys.stderr)
        # print("[vk-recv] Got user:",event.user_id,file=sys.stderr)
        name = "VK"
        if event.user_id < 0:
            name = api.groups.getById(group_id=-event.user_id)[0]["name"] + "@group.vk"
        else:
            user = api.users.get(user_ids=event.user_id)[0]
            name = user["first_name"] + " " + user["last_name"] + "@vk"
        api.messages.markAsRead(
            start_message_id=event.message_id, peer_id=event.peer_id
        )
        msg = api.messages.getById(message_ids=event.message_id)["items"][0]
        handle_message(msg)
